### ISSUE TITLE
Proposal: remove docker script from the main repo

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#494]
We don't test the docker script in https://github.com/scala-native/scala-native/tree/master/docker which means it's likely outdated and/or broken already. Given that we've had relatively straightforward setup on linux for a while now, I'd propose to remove it from the main repo.

**Comment by rberenguel** [comment]
What kind of testing are you thinking of @densh ? As mentioned in gitter we could keep it in case we need it, it's just a matter of creating an issue for what we should test then (get the docker container to run `sbt tests/run`? or testing something else?)

**Comment by densh** [comment]
If the script gets outdated, our CI should fail. If it's not tested automatically, it's likely to be broken by accident.

**Comment by densh** [comment]
Disscussion on gitter converged on moving it outside of the main repo rather than removing it altogether.

**Comment by MasseGuillaume** [comment]
I have another suggestion. We can reuse the [nix configuration](https://github.com/scala-native/scala-native/blob/master/bin/scala-native.nix#L1)
with this docker image: https://hub.docker.com/r/nixos/nix/.

**Comment by MasseGuillaume** [comment]
I get an image size of ~1GB. Is this acceptable?

**Comment by densh** [comment]
@MasseGuillaume I guess it is.

**Comment by mscharley** [comment]
Another alternative would be building something out manually. Here's an excerpt from [a build script which is basically a glorified Dockerfile](https://github.com/mscharley/scala-xoroshiro128/blob/master/circle.yml) that lets me successfully cross-build a project:

```yaml
    docker:
      - image: ubuntu:16.04
    steps:
      - run: >
          apt-get update
          && DEBIAN_FRONTEND=noninteractive apt-get install --yes
          curl git openjdk-8-jre-headless nodejs
          clang libgc-dev libunwind-dev
          && rm -rf /var/lib/apt/lists/*
          && ln -s /usr/bin/nodejs /usr/bin/node
      - run: mkdir -p ~/bin
      - run: curl -s https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt > /usr/local/bin/sbt && chmod 0755 /usr/local/bin/sbt
```
